  - name: Install PostgreSQL
    yum:
      name: postgresql-server
      state: latest

  - name: Enable PostgreSQL at boot
    service:
      name: postgresql
      enabled: yes

  - name: Debug Message
    debug:
      msg: "Either uncomment the postgres setup or manually login and initialize"

#  only run the next 2 tasks once!
#  - name: initilize postgres
#    command: postgresql-setup initdb

  - name: Enable PostgresSQL on Start
    command: chkconfig postgresql on
