  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Enable Apache at boot
    service:
      name: httpd
      enabled: yes

  - name: Start Apache
    service:
      name: httpd
      state: started
